using System.Collections.Generic;
using System.Data.Entity;
using mvcprojecttesting.Entity;

namespace mvcprojecttesting.Entity
{
    public class DataInitializater:DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            List<Category> kategoriler = new List<Category>()
            {
                new Category(){Name = "Telefon", Description = "Telefon ürünleri"},
                new Category(){Name = "Bilgisayar", Description = "Bilgisayar ürünleri"},
                new Category(){Name = "Kamera", Description = "Kamera ürünleri"},
                new Category(){Name = "Kulaklık", Description = "Kulaklık ürünleri"},
                new Category(){Name = "Beyaz Eşya", Description = "Beyaz ürünleri"}
            };

            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();

            List<Product> urunler = new List<Product>()
            {
                // Telefonlar (CategoryId = 1)
                new Product { Name = "iPhone 15 Pro Max", Description = "512GB depolama kapasitesi, Super Retina XDR OLED ekran, gelişmiş 48MP ana kamera, A17 Bionic çip, iOS 17 işletim sistemi ve uzun pil ömrü ile üst düzey bir akıllı telefon deneyimi sunar.", Price = 45000, Stock = 25, IsApproved = true, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "Samsung Galaxy S24 Ultra", Description = "1TB depolama alanı, Dynamic AMOLED 2X ekran, 200MP kamera, Snapdragon 8 Gen 3 işlemci ve S-Pen desteği ile profesyonel kullanıcılar için güçlü bir cihaz.", Price = 52000, Stock = 20, IsApproved = false, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "Xiaomi 14 Ultra", Description = "512GB depolama, AMOLED ekran, Leica ortaklığı ile geliştirilen 50MP üçlü kamera sistemi, hızlı şarj desteği ve yüksek performanslı işlemci ile fiyat/performans şampiyonu.", Price = 32000, Stock = 30, IsApproved = true, CategoryId = 1, IsHome = false, Image="1.jpg" },
                new Product { Name = "Google Pixel 8 Pro", Description = "256GB depolama, OLED ekran, gelişmiş yapay zeka destekli kamera yazılımı, Tensor G3 işlemci ve uzun yazılım desteği ile Android ekosisteminde benzersiz bir deneyim sunar.", Price = 34000, Stock = 18, IsApproved = false, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "OnePlus 12", Description = "512GB depolama, AMOLED ekran, 50MP ana kamera, Snapdragon 8 Gen 3 işlemci ve hızlı şarj teknolojisi ile yüksek performanslı bir akıllı telefon.", Price = 28000, Stock = 22, IsApproved = true, CategoryId = 1, IsHome = false, Image="1.jpg" },
                new Product { Name = "Huawei Mate 60 Pro", Description = "256GB depolama, OLED ekran, 50MP çok yönlü kamera sistemi, uzun ömürlü pil ve HarmonyOS işletim sistemi ile dikkat çeken güçlü bir cihaz.", Price = 30000, Stock = 28, IsApproved = true, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "Oppo Find X6 Pro", Description = "512GB depolama, AMOLED ekran, Hasselblad iş birliği ile geliştirilmiş kamera sistemi, Snapdragon işlemci ve şık tasarım ile amiral gemisi özellikleri sunar.", Price = 31000, Stock = 26, IsApproved = false, CategoryId = 1, IsHome = false, Image="1.jpg" },
                new Product { Name = "Sony Xperia 1 V", Description = "256GB depolama, 4K OLED ekran, profesyonel kamera modları, Snapdragon işlemci ve dayanıklı tasarımıyla fotoğrafçılar için özel bir cihaz.", Price = 36000, Stock = 14, IsApproved = true, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "Asus ROG Phone 7", Description = "512GB depolama, AMOLED ekran, oyun odaklı soğutma sistemi, Snapdragon 8 Gen 2 işlemci ve yüksek kapasiteli batarya ile mobil oyun tutkunları için geliştirildi.", Price = 27000, Stock = 19, IsApproved = true, CategoryId = 1, IsHome = false, Image="1.jpg" },
                new Product { Name = "Realme GT 5 Pro", Description = "256GB depolama, AMOLED ekran, 50MP ana kamera, Snapdragon 8 Gen 2 işlemci ve uygun fiyatıyla öne çıkan güçlü bir telefon.", Price = 21000, Stock = 32, IsApproved = false, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "Honor Magic 6 Pro", Description = "512GB depolama, OLED ekran, güçlü kamera sistemi, Snapdragon işlemci ve yüksek pil kapasitesiyle amiral gemisi seviyesinde özellikler sunar.", Price = 29000, Stock = 24, IsApproved = true, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "Motorola Edge 40 Pro", Description = "256GB depolama, pOLED ekran, Snapdragon 8 Gen 2 işlemci, 60MP kamera ve hızlı şarj özelliği ile orta-üst segmentte öne çıkar.", Price = 25000, Stock = 27, IsApproved = false, CategoryId = 1, IsHome = false, Image="1.jpg" },
                new Product { Name = "Vivo X100 Pro", Description = "512GB depolama, AMOLED ekran, Zeiss lensli kamera sistemi, Dimensity 9300 işlemci ve uzun ömürlü batarya ile dikkat çekici bir cihaz.", Price = 33000, Stock = 17, IsApproved = true, CategoryId = 1, IsHome = true, Image="1.jpg" },
                new Product { Name = "ZTE Nubia Z50 Ultra", Description = "256GB depolama, AMOLED ekran, güçlü kamera performansı, Snapdragon işlemci ve oyun odaklı özellikleri ile fiyat/performans ürünü.", Price = 22000, Stock = 21, IsApproved = true, CategoryId = 1, IsHome = false, Image="1.jpg" },
                new Product { Name = "Meizu 20 Pro", Description = "256GB depolama, AMOLED ekran, Snapdragon 8 Gen 2 işlemci, güçlü kamera ve şık tasarım ile kullanıcıların ilgisini çeken bir akıllı telefon.", Price = 20000, Stock = 29, IsApproved = false, CategoryId = 1, IsHome = true, Image="1.jpg" },

                // Bilgisayarlar (CategoryId = 2)
                new Product { Name = "Lenovo ThinkPad X1 Carbon", Description = "14 inç ultra hafif tasarım, Intel i7 işlemci, 16GB RAM ve 512GB SSD ile donatılmış, kurumsal kullanım için güvenilir ve dayanıklı bir dizüstü bilgisayar. Yüksek batarya ömrü ve sağlam kasa yapısıyla öne çıkar.", Price = 38000, Stock = 18, IsApproved = true, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "HP Spectre x360", Description = "13.5 inç dokunmatik OLED ekran, Intel i5 işlemci, 16GB RAM ve 512GB SSD ile performans ve taşınabilirliği bir araya getiren 2'si 1 arada dizüstü bilgisayar. Şık ve ince tasarımı ile dikkat çeker.", Price = 34000, Stock = 20, IsApproved = false, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "MSI Raider GE78", Description = "Intel i9 işlemci, 32GB RAM, 2TB SSD ve RTX 4080 ekran kartı ile profesyonel oyuncular için geliştirilen yüksek performanslı bir laptop. RGB klavyesi ve güçlü soğutma sistemiyle uzun oyun seansları için uygundur.", Price = 72000, Stock = 10, IsApproved = true, CategoryId = 2, IsHome = false, Image="2.jpg" },
                new Product { Name = "Acer Predator Helios 16", Description = "16 inç QHD ekran, Intel i7 işlemci, 16GB RAM ve RTX 4070 ekran kartı ile donatılmış güçlü bir oyun bilgisayarı. Yüksek yenileme hızına sahip ekranıyla akıcı oyun deneyimi sağlar.", Price = 56000, Stock = 14, IsApproved = false, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Razer Blade 15", Description = "Intel i7 işlemci, 32GB RAM, 1TB SSD ve RTX 4060 ekran kartı ile ultra ince kasada yüksek performans sunar. Profesyonel oyuncular ve içerik üreticileri için tasarlanmıştır.", Price = 60000, Stock = 8, IsApproved = true, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Huawei MateBook X Pro", Description = "13.9 inç 3K dokunmatik ekran, Intel i7 işlemci, 16GB RAM ve 1TB SSD ile donatılmış hafif ve şık bir ultrabook. Taşınabilirliği ve premium tasarımıyla ön plana çıkar.", Price = 31000, Stock = 22, IsApproved = true, CategoryId = 2, IsHome = false, Image="2.jpg" },
                new Product { Name = "Gigabyte Aero 16", Description = "Intel i9 işlemci, 32GB RAM, 1TB SSD ve RTX 4070 ekran kartı ile içerik üreticilerine hitap eden güçlü bir laptop. Renk doğruluğu yüksek OLED ekranı profesyonel grafik tasarımcılar için idealdir.", Price = 58000, Stock = 7, IsApproved = false, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Microsoft Surface Laptop Studio", Description = "14.4 inç PixelSense Flow dokunmatik ekran, Intel i7 işlemci, 16GB RAM ve 512GB SSD ile yaratıcı profesyoneller için geliştirilmiş çok yönlü bir dizüstü bilgisayar.", Price = 42000, Stock = 13, IsApproved = true, CategoryId = 2, IsHome = false, Image="2.jpg" },
                new Product { Name = "Alienware x17 R2", Description = "17.3 inç FHD ekran, Intel i9 işlemci, 32GB RAM, 1TB SSD ve RTX 3080Ti ekran kartı ile donatılmış efsanevi bir oyun canavarı. Yüksek performansı ve şık tasarımıyla oyuncuların rüyasıdır.", Price = 80000, Stock = 5, IsApproved = true, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Samsung Galaxy Book3 Ultra", Description = "16 inç AMOLED ekran, Intel i9 işlemci, 32GB RAM ve RTX 4070 ekran kartı ile donatılmış premium bir dizüstü bilgisayar. Yüksek performansı ve uzun batarya ömrüyle öne çıkar.", Price = 49000, Stock = 16, IsApproved = false, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Asus ZenBook Pro Duo 15", Description = "Çift ekranlı yenilikçi tasarımıyla dikkat çeken bu laptop, Intel i7 işlemci, 16GB RAM, 1TB SSD ve RTX 3060 ekran kartına sahiptir. Multitasking ve içerik üretimi için idealdir.", Price = 47000, Stock = 11, IsApproved = true, CategoryId = 2, IsHome = false, Image="2.jpg" },
                new Product { Name = "Dell Alienware m15", Description = "15.6 inç QHD ekran, Intel i7 işlemci, 16GB RAM ve RTX 3070 ekran kartı ile güçlü bir oyun bilgisayarı. Hafif tasarımı sayesinde taşınabilirliği yüksek bir gaming laptopudur.", Price = 52000, Stock = 9, IsApproved = false, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Apple MacBook Air M2", Description = "Apple’ın M2 çipiyle donatılmış, 13.6 inç Retina ekran, 8GB RAM ve 512GB SSD’ye sahip hafif ve taşınabilir bir laptop. Günlük kullanım ve iş için idealdir.", Price = 28000, Stock = 25, IsApproved = true, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Lenovo Legion 7", Description = "16 inç WQXGA ekran, AMD Ryzen 9 işlemci, 32GB RAM ve RTX 4080 ekran kartı ile üst düzey oyun performansı sunar. Güçlü soğutma sistemi sayesinde uzun süreli kullanımda stabil kalır.", Price = 69000, Stock = 6, IsApproved = false, CategoryId = 2, IsHome = true, Image="2.jpg" },
                new Product { Name = "Toshiba Dynabook Tecra", Description = "Kurumsal kullanıcılar için geliştirilmiş, Intel i5 işlemci, 8GB RAM ve 256GB SSD’ye sahip dayanıklı bir iş bilgisayarı. Güvenlik özellikleriyle donatılmıştır.", Price = 22000, Stock = 28, IsApproved = true, CategoryId = 2, IsHome = false, Image="2.jpg" },

                // Kameralar (CategoryId = 3)
                new Product { Name = "Canon EOS R5", Description = "45MP çözünürlüklü full frame sensör, 8K video kaydı ve gelişmiş Dual Pixel otomatik odaklama sistemi ile profesyonel fotoğrafçılar için mükemmel bir aynasız fotoğraf makinesi. Yüksek hızlı seri çekim özelliğiyle spor ve aksiyon fotoğrafçılığına uygundur.", Price = 65000, Stock = 6, IsApproved = true, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Nikon Z9", Description = "Stacked CMOS sensör, 45.7MP çözünürlük, 8K video desteği ve gelişmiş yapay zeka tabanlı takip sistemi ile profesyonel seviye çekimler için geliştirilmiştir. Dayanıklı gövdesiyle zorlu koşullarda kullanılabilir.", Price = 72000, Stock = 4, IsApproved = false, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Sony A1", Description = "50MP full frame sensör, 8K video kaydı, 30fps seri çekim ve gelişmiş otomatik odaklama özellikleri ile Sony’nin en üst düzey aynasız kamerası. Profesyonel hem fotoğraf hem video çekimleri için idealdir.", Price = 75000, Stock = 3, IsApproved = true, CategoryId = 3, IsHome = false, Image="3.jpg" },
                new Product { Name = "Fujifilm X-T5", Description = "40MP APS-C sensör, 6K video kaydı, retro tasarım ve gelişmiş renk profilleriyle Fujifilm’in en güçlü aynasız modellerinden biri. Hem profesyoneller hem de fotoğraf tutkunları için uygundur.", Price = 36000, Stock = 10, IsApproved = true, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Panasonic Lumix S5 II", Description = "24MP full frame sensör, 6K video kaydı, çift yerleşik görüntü sabitleme ve gelişmiş odaklama sistemine sahip kompakt ve güçlü bir kamera. Video içerik üreticileri için idealdir.", Price = 29000, Stock = 12, IsApproved = false, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Olympus OM-D E-M1 Mark III", Description = "20MP Micro Four Thirds sensör, 4K video kaydı ve gelişmiş görüntü sabitleme özelliği ile seyahat fotoğrafçıları için hafif ve dayanıklı bir seçenek. Toz ve suya dayanıklı gövdesiyle zorlu ortamlara uygundur.", Price = 21000, Stock = 15, IsApproved = true, CategoryId = 3, IsHome = false, Image="3.jpg" },
                new Product { Name = "Leica SL2-S", Description = "24MP full frame sensör, 4K video kaydı ve Leica’nın eşsiz renk işleme teknolojisiyle hem profesyonel fotoğrafçılara hem de video içerik üreticilerine hitap eden premium bir model.", Price = 95000, Stock = 2, IsApproved = false, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Canon EOS 90D", Description = "32.5MP APS-C sensör, 4K video kaydı ve yüksek çözünürlüklü fotoğraf performansı ile hem amatör hem de yarı profesyonel kullanıcılar için ideal bir DSLR kamera.", Price = 18000, Stock = 20, IsApproved = true, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Nikon D850", Description = "45.7MP çözünürlük, 4K video kaydı, geniş dinamik aralık ve mükemmel düşük ışık performansı ile profesyonel DSLR kameralar arasında efsaneleşmiş bir modeldir.", Price = 42000, Stock = 7, IsApproved = true, CategoryId = 3, IsHome = false, Image="3.jpg" },
                new Product { Name = "Sony A7R V", Description = "61MP çözünürlük, yapay zeka tabanlı nesne tanıma, 8K video kaydı ve geliştirilmiş otomatik odaklama özellikleri ile yüksek çözünürlük isteyen profesyoneller için özel tasarlanmış bir aynasız kamera.", Price = 67000, Stock = 5, IsApproved = false, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Fujifilm GFX100S", Description = "102MP orta format sensör, 4K video kaydı ve olağanüstü dinamik aralık sunan bu kamera, moda, stüdyo ve manzara fotoğrafçılığında profesyonellerin tercihi.", Price = 120000, Stock = 1, IsApproved = true, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Panasonic GH6", Description = "25MP Micro Four Thirds sensör, 5.7K video kaydı ve sinematik çekim modlarıyla video prodüksiyon dünyasında öne çıkan bir kamera. Kompakt tasarımıyla taşınabilirliği yüksektir.", Price = 27000, Stock = 9, IsApproved = false, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Canon EOS R10", Description = "24MP APS-C sensör, 4K 60fps video kaydı, gelişmiş otomatik odaklama ve kompakt gövdesiyle yeni başlayanlar için fiyat-performans açısından öne çıkan bir model.", Price = 15000, Stock = 25, IsApproved = true, CategoryId = 3, IsHome = false, Image="3.jpg" },
                new Product { Name = "Nikon Z50", Description = "20.9MP APS-C sensör, 4K video kaydı, taşınabilir gövde yapısı ve kullanımı kolay arayüzü ile amatör fotoğrafçılara hitap eden aynasız bir kamera.", Price = 14000, Stock = 18, IsApproved = true, CategoryId = 3, IsHome = true, Image="3.jpg" },
                new Product { Name = "Sony FX3", Description = "Profesyonel sinema kameralarıyla aynı teknolojiyi kompakt gövdede sunan bu model, 12MP full frame sensör, 4K 120fps video kaydı ve gelişmiş düşük ışık performansıyla video prodüksiyon dünyasında tercih edilmektedir.", Price = 58000, Stock = 4, IsApproved = false, CategoryId = 3, IsHome = true, Image="3.jpg" },

                // Kulaklıklar (CategoryId = 4)
                new Product { Name = "Sony WF-1000XM4", Description = "Tamamen kablosuz kulak içi tasarımı, güçlü bas tepkisi, aktif gürültü engelleme teknolojisi ve uzun pil ömrüyle hem müzik hem de çağrı deneyiminde yüksek performans sunar.", Price = 5500, Stock = 35, IsApproved = true, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Bose 700", Description = "Şık tasarımı, üstün gürültü engelleme teknolojisi, dengeli ses profili ve konforlu kulak yastıkları ile uzun süreli kullanımda bile rahatlık sunar.", Price = 7200, Stock = 28, IsApproved = false, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Sennheiser Momentum 4 Wireless", Description = "Gelişmiş ses kalitesi, 60 saate varan uzun pil ömrü, konforlu tasarımı ve Bluetooth 5.2 desteği ile premium bir müzik dinleme deneyimi sağlar.", Price = 8000, Stock = 20, IsApproved = true, CategoryId = 4, IsHome = false, Image="4.jpg" },
                new Product { Name = "Apple AirPods Pro 2", Description = "Aktif gürültü engelleme, şeffaflık modu, MagSafe uyumlu şarj kutusu ve Apple ekosistemiyle tam entegrasyon sayesinde kablosuz kulak içi kulaklıklar arasında öne çıkıyor.", Price = 6500, Stock = 45, IsApproved = true, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Jabra Elite 85h", Description = "Uzun pil ömrü, suya dayanıklı tasarımı, güçlü mikrofon performansı ve kişiselleştirilebilir ses profilleri ile hem iş hem eğlence için ideal bir kulaklık.", Price = 4800, Stock = 32, IsApproved = false, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Bang & Olufsen Beoplay H95", Description = "Lüks tasarım, üstün malzeme kalitesi, gelişmiş aktif gürültü engelleme teknolojisi ve yüksek çözünürlüklü ses performansı ile premium bir kulaklık deneyimi sunar.", Price = 18000, Stock = 5, IsApproved = true, CategoryId = 4, IsHome = false, Image="4.jpg" },
                new Product { Name = "Marshall Monitor II ANC", Description = "Klasik Marshall tasarımı, güçlü basları, aktif gürültü engelleme özelliği ve katlanabilir yapısıyla hem şık hem de işlevsel bir kulaklık modelidir.", Price = 6200, Stock = 25, IsApproved = false, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Beats Studio3 Wireless", Description = "Apple W1 çipi, aktif gürültü engelleme, yüksek bas performansı ve uzun pil ömrü ile özellikle genç kullanıcıların tercihi olan kablosuz kulak üstü kulaklık.", Price = 5600, Stock = 30, IsApproved = true, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "AKG N700NC M2", Description = "Stüdyo kalitesinde ses deneyimi, aktif gürültü engelleme teknolojisi, uzun pil ömrü ve ergonomik tasarımıyla öne çıkan bir kulak üstü model.", Price = 4500, Stock = 27, IsApproved = true, CategoryId = 4, IsHome = false, Image="4.jpg" },
                new Product { Name = "Anker Soundcore Life Q35", Description = "Uygun fiyatına rağmen yüksek ses kalitesi, hibrit gürültü engelleme özelliği, LDAC desteği ve rahat tasarımıyla fiyat-performans açısından öne çıkar.", Price = 3200, Stock = 40, IsApproved = false, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Shure AONIC 50", Description = "Profesyonel ses mühendisliği kalitesi, kablosuz bağlantı, güçlü aktif gürültü engelleme ve dayanıklı tasarımıyla üst düzey bir kulaklık.", Price = 9000, Stock = 12, IsApproved = true, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Skullcandy Crusher Evo", Description = "Titreşimli bas teknolojisi, özelleştirilebilir ses profilleri ve uzun pil ömrüyle özellikle bas severler için tasarlanmış bir kulaklık.", Price = 3800, Stock = 38, IsApproved = false, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Logitech G Pro X Wireless", Description = "Oyun severler için tasarlanmış, Blue VO!CE mikrofon teknolojisi, düşük gecikmeli kablosuz bağlantı ve uzun süreli konfor sağlayan kulak üstü kulaklık.", Price = 5200, Stock = 22, IsApproved = true, CategoryId = 4, IsHome = false, Image="4.jpg" },
                new Product { Name = "HyperX Cloud Alpha Wireless", Description = "Gaming odaklı, 300 saate varan pil ömrü, DTS Headphone:X 3D ses desteği ve rahat yastıklarıyla oyun deneyimini üst seviyeye taşıyan bir kulaklık.", Price = 4700, Stock = 28, IsApproved = true, CategoryId = 4, IsHome = true, Image="4.jpg" },
                new Product { Name = "Razer BlackShark V2 Pro", Description = "Esports odaklı tasarım, yüksek kaliteli mikrofon, THX Spatial Audio desteği ve konforlu kulak yastıkları ile profesyonel oyuncular için geliştirilmiştir.", Price = 4900, Stock = 26, IsApproved = false, CategoryId = 4, IsHome = true, Image="4.jpg" }
            };

            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }
            context.SaveChanges();

            base.Seed(context);
        }
    }
}
